#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
export PATH=$PATH:/home/jaypei/bin


export PERL_LOCAL_LIB_ROOT="/home/jaypei/perl5";
export PERL_MB_OPT="--install_base /home/jaypei/perl5";
export PERL_MM_OPT="INSTALL_BASE=/home/jaypei/perl5";
export PERL5LIB="/home/jaypei/perl5/lib/perl5/i686-linux-thread-multi:/home/jaypei/perl5/lib/perl5";
export PATH="/home/jaypei/perl5/bin:$PATH";
