#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice

#export LANG="zh_CN.UTF-8"
#export LC_ALL="zh_CN.UTF-8"
#export LC_CTYPE="zh_CN.UTF-8"


xinput set-int-prop 12 "Device Enabled" 8 0

# ibus
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus


exec ck-launch-session dbus-launch --exit-with-session startxfce4
xinput set-int-prop 12 "Device Enabled" 8 0



